#!/usr/bin/env python3
"""Build js/search-index.js for the header search.

Run from the site root after changing page content:
    python3 tools/build-search-index.py

Each page is split into chunks at its h1/h2/h3 headings. A chunk links to the
nearest section id above it (e.g. services/#asbestos), so results land on the
right part of the page. The header nav, footer, scripts and hidden elements are
skipped.
"""
import json, os, re
from html.parser import HTMLParser

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGES = [
    ('index.html', 'Home'),
    ('services/index.html', 'Services'),
    ('sectors/index.html', 'Sectors'),
    ('about/index.html', 'About'),
    ('venm-certificate/index.html', 'VENM Certificates'),
    ('news/index.html', 'News & Insights'),
    ('contact/index.html', 'Contact'),
]
SKIP_TAGS = {'script', 'style', 'noscript', 'svg', 'nav', 'footer', 'form', 'template'}
# ids that are layout hooks, not destinations
IGNORE_IDS = {'work-track', 'dot-0', 'dot-1', 'article-grid', 'news-empty', 'enquiry-form'}
# subheadings too generic to stand alone - folded into the section above
MERGE = {'Core services', 'Where this is applied', 'Typical work includes'}
# headings that aren't useful as results
DROP = {'No articles published yet', 'Direct contact', 'Send us your project details.'}
VOID = {'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'source', 'track', 'wbr'}


class Chunker(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.skip = 0            # depth inside skipped elements
        self.stack = []
        self.anchor = ''
        self.chunks = []
        self.cur = None
        self.in_heading = None

    def start(self, heading, anchor):
        self.cur = {'heading': heading, 'anchor': anchor, 'text': []}
        self.chunks.append(self.cur)

    def gap(self):
        # element boundaries (<br>, <span>, <li>...) separate words in the rendered page
        if self.in_heading is not None:
            self.in_heading.append(' ')
        elif self.cur is not None:
            self.cur['text'].append(' ')

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if not self.skip:
            self.gap()
        hidden = 'hidden' in a or 'display:none' in (a.get('style') or '').replace(' ', '')
        if tag in VOID:
            return
        self.stack.append(tag)
        if self.skip or tag in SKIP_TAGS or hidden or a.get('aria-hidden') == 'true':
            self.skip += 1
            return
        if a.get('id') and a['id'] not in IGNORE_IDS and tag in ('section', 'article', 'header', 'div', 'main'):
            self.anchor = a['id']
        if tag in ('h1', 'h2', 'h3'):
            self.in_heading = []

    def handle_endtag(self, tag):
        if not self.skip:
            self.gap()
        if tag in VOID or not self.stack:
            return
        # pop to the matching tag (tolerates sloppy markup)
        while self.stack:
            t = self.stack.pop()
            if self.skip:
                self.skip -= 1
                if t == tag:
                    return
                continue
            if t == tag:
                break
        if tag in ('h1', 'h2', 'h3') and self.in_heading is not None:
            text = ' '.join(''.join(self.in_heading).split())
            self.in_heading = None
            if text:
                self.start(text, self.anchor)

    def handle_data(self, data):
        if self.skip:
            return
        if self.in_heading is not None:
            self.in_heading.append(data)
        elif self.cur is not None:
            self.cur['text'].append(data)


def build():
    out = []
    for path, page in PAGES:
        html = open(os.path.join(ROOT, path), encoding='utf-8').read()
        html = re.sub(r'<!--.*?-->', ' ', html, flags=re.S)
        body = html[html.find('<body'):]
        p = Chunker()
        p.feed(body)
        url_base = '' if path == 'index.html' else path[:-len('index.html')]
        merged = []
        for c in p.chunks:
            if c['heading'] in DROP:
                continue
            if c['heading'] in MERGE and merged and merged[-1]['anchor'] == c['anchor']:
                merged[-1]['text'] += [' ', c['heading'], ': '] + c['text']
                continue
            merged.append(c)
        for c in merged:
            text = ' '.join(''.join(c['text']).split())[:4000]
            url = url_base + ('#' + c['anchor'] if c['anchor'] else '')
            out.append({'page': page, 'url': url or './', 'heading': c['heading'], 'text': text})
    js = ('/* Generated by tools/build-search-index.py - do not edit by hand. */\n'
          'window.GETEX_SEARCH_INDEX = ' + json.dumps(out, ensure_ascii=False, indent=0) + ';\n')
    open(os.path.join(ROOT, 'js', 'search-index.js'), 'w', encoding='utf-8').write(js)
    print(f'{len(out)} entries written to js/search-index.js')


if __name__ == '__main__':
    build()
